# Generated by Django 3.2.13 on 2023-03-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20230326_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioural',
            name='week',
            field=models.IntegerField(default=None, verbose_name='Week'),
        ),
    ]
