# Generated by Django 3.2.13 on 2023-03-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_behavioural_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleinfo',
            name='ca_weight',
        ),
        migrations.RemoveField(
            model_name='moduleinfo',
            name='exam_weight',
        ),
        migrations.AddField(
            model_name='module',
            name='ca_weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='module',
            name='exam_weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='behavioural',
            name='attendance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
