# Generated by Django 3.2.13 on 2023-03-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_cognitive_overall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cognitive',
            name='coursework',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cognitive',
            name='exam',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cognitive',
            name='overall',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
