# Generated by Django 3.2.13 on 2023-03-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_affective_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='week',
        ),
        migrations.AddField(
            model_name='moduleinfo',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affective',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
