# Generated by Django 3.2.13 on 2023-03-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20230327_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleinfo',
            name='answer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
    ]
